### ISSUE TITLE
npm start failed in windows 10

### ISSUE THREAD

**Issue by ruixiwu** [Autodesk-Forge/forge-rcdb.nodejs#21]
hello, all, 
after a hard compiling with "npm install", I did finished it with obvious error
then I try to run with "npm start", it get failed , and report "Error: ENOENT: no such file or directory, scandir 'D:\_h5_work\forge-rcdb.nodejs0927\dist'   "

what is  that "dist"?

**D:\_h5_work\forge-rcdb.nodejs0927>npm start

> forge-rcdb@4.0.0 start D:\_h5_work\forge-rcdb.nodejs0927
> node bin/start.js

fs.js:953
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'D:\_h5_work\forge-rcdb.nodejs0927\dist'
    at Error (native)
    at Object.fs.readdirSync (fs.js:953:18)
    at findAllCompressionFiles (D:\_h5_work\forge-rcdb.nodejs0927\node_modules\express-static-gzip\index.js:127:24)
    at expressStaticGzip (D:\_h5_work\forge-rcdb.nodejs0927\node_modules\express-static-gzip\index.js:28:9)
    at Object.<anonymous> (D:/_h5_work/forge-rcdb.nodejs0927/src/server/index.js:230:11)
    at Module._compile (module.js:570:32)
    at loader (D:\_h5_work\forge-rcdb.nodejs0927\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\_h5_work\forge-rcdb.nodejs0927\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\_h5_work\forge-rcdb.nodejs0927\bin\start.js:24:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\programfiles\\nodejs\\node.exe" "D:\\programfiles\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! forge-rcdb@4.0.0 start: `node bin/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the forge-rcdb@4.0.0 start script 'node bin/start.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the forge-rcdb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/start.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs forge-rcdb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls forge-rcdb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\_h5_work\forge-rcdb.nodejs0927\npm-debug.log

D:\_h5_work\forge-rcdb.nodejs0927>**

**Comment by ruixiwu** [comment]
thanks  leefsmp, 
this is the solution:
(1) install the canvas right first ,  refer to https://github.com/Automattic/node-canvas/wiki/Installation---Windows
it's hard time to install node-canvas; make you install manually with all those steps, here I forget to install the GTK2 in right position, and lead to the error.
make sure you installed VC++ 2013 or VC++ 2015. 

then "npm install " run successfully. 
(2) before "npm start", you should set these environments for windows 10

FORGE_DEV_CLIENT_ID="your_client_id"
FORGE_DEV_CLIENT_SECRET="your_client_secret"
NODE_ENV=development

here "NODE_ENV=development" means the project will be build again every time.
if set as NODE_ENV=production, you should do  "npm run build-prod && npm start"

finally, compile successfully, enjoy youself!
