### ISSUE TITLE
connect the db error ? in windows 10

### ISSUE THREAD

**Issue by ruixiwu** [Autodesk-Forge/forge-rcdb.nodejs#22]
hello, all, 
I did startup the project  with  "npm run build-prod && npm start"
and  I  did startup the mongodb, and created the database according to ".\config\production.config.js"
the mongodb has no the authentication limitation. it runs like this 
![2017-09-29_1-29-22](https://user-images.githubusercontent.com/9555002/30981068-c36f0214-a4b5-11e7-9381-aa64d47bdff5.png)

but the system throws the error to connect the mongodb

====:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

> forge-rcdb@4.0.0 start D:\_h5_work\forge-rcdb.nodejs0927
> node bin/start.js

Server listening on PORT: 3000
ENV: undefined
uncaughtException
{ MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (D:\_h5_work\forge-rcdb.nodejs0927\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (D:\_h5_work\forge-rcdb.nodejs0927\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Connection.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (D:\_h5_work\forge-rcdb.nodejs0927\node_modules\mongodb-core\lib\connection\connection.js:187:49)
    at Socket.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'MongoError',
  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (D:\_h5_work\forge-rcdb.nodejs0927\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:96:13)
                                                                                                    build [=============                                                                              build [=================   ] 86% (65.2 sec                                                        build [====================] 100% (173.6 seconds)
    at Connection.g (events.js:292:16)

**Comment by ruixiwu** [comment]
finally, I set those varibles for the windows
then it works with development mode

FORGE_DEV_CLIENT_ID="your_client_id"
FORGE_DEV_CLIENT_SECRET="your_client_secret"
NODE_ENV=development
