### ISSUE TITLE
setup in ubuntu failed

### ISSUE THREAD

**Issue by johnfelipe** [Autodesk-Forge/forge-rcdb.nodejs#33]
bro this is my steps:

	git clone https://github.com/Autodesk-Forge/forge-rcdb.nodejs.git

	cd forge-rcdb.nodejs/

	npm install

	export NODE_ENV=development

	sudo nano /home/felipe/forge-rcdb.nodejs/config/development.config.js

	##
	const PORT = 3012
	##

	sudo nano /home/felipe/forge-rcdb.nodejs/src/server/index.js

	##
		const server = app.listen(
		  process.env.PORT || 3012, () => {
	##

	export FORGE_CLIENT_ID=ls......5R
	export FORGE_CLIENT_SECRET=K........5

when compile show me this:

	felipe@devpythonodejs:~/forge-rcdb.nodejs$ npm start

	> forge-rcdb@4.0.0 start /home/felipe/forge-rcdb.nodejs
	> node bin/start.js

	fs.js:953
	  return binding.readdir(pathModule._makeLong(path), options.encoding);
					 ^

	Error: ENOENT: no such file or directory, scandir '/home/felipe/forge-rcdb.nodejs/dist'
		at Error (native)
		at Object.fs.readdirSync (fs.js:953:18)
		at findAllCompressionFiles (/home/felipe/forge-rcdb.nodejs/node_modules/express-static-gzip/index.js:127:24)
		at expressStaticGzip (/home/felipe/forge-rcdb.nodejs/node_modules/express-static-gzip/index.js:28:9)
		at Object.<anonymous> (/home/felipe/forge-rcdb.nodejs/src/server/index.js:230:11)
		at Module._compile (module.js:570:32)
		at loader (/home/felipe/forge-rcdb.nodejs/node_modules/babel-register/lib/node.js:144:5)
		at Object.require.extensions.(anonymous function) [as .js] (/home/felipe/forge-rcdb.nodejs/node_modules/babel-register/lib/node.js:154:7)
		at Module.load (module.js:487:32)
		at tryModuleLoad (module.js:446:12)
		at Function.Module._load (module.js:438:3)
		at Module.require (module.js:497:17)
		at require (internal/module.js:20:19)
		at Object.<anonymous> (/home/felipe/forge-rcdb.nodejs/bin/start.js:24:3)
		at Module._compile (module.js:570:32)
		at Object.Module._extensions..js (module.js:579:10)

	npm ERR! Linux 4.4.0-31-generic
	npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
	npm ERR! node v6.11.4
	npm ERR! npm  v3.10.10
	npm ERR! code ELIFECYCLE
	npm ERR! forge-rcdb@4.0.0 start: `node bin/start.js`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the forge-rcdb@4.0.0 start script 'node bin/start.js'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the forge-rcdb package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node bin/start.js
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs forge-rcdb
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls forge-rcdb
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /home/felipe/forge-rcdb.nodejs/npm-debug.log

show me how solve that issue

**Comment by leefsmp** [comment]
with NODE_ENV=development you should use `FORGE_DEV_CLIENT_ID` and `FORGE_DEV_CLIENT_SECRET`. Then also use `HOT_RELOADING=true`.  You need to populate a local database (in dev) in order to run that sample.

**Comment by johnfelipe** [comment]
this is log

https://paste.md-5.net/vifugodasa.pl

But how can add my model?

http://200.122.209.133:3012/
