### ISSUE TITLE
Production error: No module './static'

### ISSUE THREAD

**Issue by yangdihan** [Autodesk-Forge/forge-rcdb.nodejs#59]
I am trying to build and run this project in production env. I work on Windows Powershell, but the following commands:

```
npm run build-prod
 $env:NODE_ENV ="production"
npm start
```
 but I got the following errors:

```
> node bin/start.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './static'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\dyang\Documents\forge-rcdb.nodejs\bin\start.js:15:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! forge-rcdb@4.0.0 start: `node bin/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the forge-rcdb@4.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

I tried to do 
`npm install node-static`
but the error is still the same. Can someone help me with this? what is the ./static for?

**Comment by yangdihan** [comment]
use `npm run build-server` instead of `npm run build-prod` solves the problem. Not sure other potential effects.

**Comment by yangdihan** [comment]
use `npm run build-server` instead of `npm run build-prod` solves the problem. Not sure other potential effects.
