### ISSUE TITLE
when npm start ,   there is  erroor  api_key is a required parameter

### ISSUE THREAD

**Issue by kingov** [Autodesk-Forge/forge-rcdb.nodejs#73]
/Users/wangzheng/threejs/forge-rcdb.nodejs/node_modules/webpurify/dist/configuration.js:51
      throw new Error('api_key is a required parameter');
      ^

Error: api_key is a required parameter
    at Configuration.get api_key [as api_key] (/Users/wangzheng/threejs/forge-rcdb.nodejs/node_modules/webpurify/dist/configuration.js:51:13)
    at Configuration.get config [as config] (/Users/wangzheng/threejs/forge-rcdb.nodejs/node_modules/webpurify/dist/configuration.js:38:23)
    at new WebPurify (/Users/wangzheng/threejs/forge-rcdb.nodejs/node_modules/webpurify/dist/webpurify.js:23:34)
    at module.exports (/Users/wangzheng/threejs/forge-rcdb.nodejs/src/server/api/endpoints/materials.js:40:14)
    at Object.<anonymous> (/Users/wangzheng/threejs/forge-rcdb.nodejs/src/server/index.js:170:27)
    at Module._compile (module.js:653:30)
    at loader (/Users/wangzheng/threejs/forge-rcdb.nodejs/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/wangzheng/threejs/forge-rcdb.nodejs/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

**Comment by kingov** [comment]
i have resolve this problem ,  set env   WEBPURIFY_API_KEY   a  value

**Comment by PavelBalobanov** [comment]
> i have resolve this problem , set env WEBPURIFY_API_KEY a value
Hi! Tell me, please, what value?

**Comment by libvarun** [comment]
https://www.webpurify.com/
create account and trial key here. Then set it as the WEBPURIFY_API_KEY
