### ISSUE TITLE
question about mongobd and Promise  Promise when start 

### ISSUE THREAD

**Issue by xuehang1** [Autodesk-Forge/forge-rcdb.nodejs#86]
I git clone code from remastered and then  "yarn start" have some error :
**1、**
**Server listening on PORT: 3000
ENV: undefined
Connected to MongoDB Database: admin
uncaughtException
{ MongoError: Authentication failed.
    at Function.MongoError.create (/forgeview/forge-rcdb.nodejs/node_modules/connect-mongo/node_modules/mongodb-core/lib/error.js:31:11)
    at/forgeview/forge-rcdb.nodejs/node_modules/connect-mongo/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/forgeview/forge-rcdb.nodejs/node_modules/connect-mongo/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at Connection.messageHandler (/forgeview/forge-rcdb.nodejs/node_modules/connect-mongo/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at Socket.<anonymous> (/forgeview/forge-rcdb.nodejs/node_modules/connect-mongo/node_modules/mongodb-core/lib/connection/connection.js:333:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
  name: 'MongoError',
  message: 'Authentication failed.',
  ok: 0,
  errmsg: 'Authentication failed.',
  code: 18,
  codeName: 'AuthenticationFailed' }**

**2、
Unhandled Rejection at: Promise  Promise {
  <rejected> { developerMessage:
     'The required parameter(s) client_id,client_secret not present in the request',
    userMessage: '',
    errorCode: 'AUTH-008',
    'more info':
     'http://developer.api.autodesk.com/documentation/v1/errors/AUTH-008' } }  reason:  { developerMessage:
   'The required parameter(s) client_id,client_secret not present in the request',**

**3、
Error: Not connected
    at Promise (/forgeview/forge-rcdb.nodejs/node_modules/connect-mongo/src/index.js:170:18)
    at new Promise (<anonymous>)
    at MongoStore.collectionReady (/forgeview/forge-rcdb.nodejs/node_modules/connect-mongo/src/index.js:163:19)
    at MongoStore.get (/forgeview/forge-rcdb.nodejs/node_modules/connect-mongo/src/index.js:187:32)
    at session (/forgeview/forge-rcdb.nodejs/node_modules/express-session/index.js:474:11)
    at Layer.handle [as handle_request] (/forgeview/forge-rcdb.nodejs/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/forgeview/forge-rcdb.nodejs/node_modules/express/lib/router/index.js:317:13)
    at /forgeview/forge-rcdb.nodejs/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/forgeview/forge-rcdb.nodejs/node_modules/express/lib/router/index.js:335:12)
    at next (/forgeview/forge-rcdb.nodejs/node_modules/express/lib/router/index.js:275:10)
Cleaning Dir: /forgeview/forge-rcdb.nodejs/TMP**

**Comment by dukedhx** [comment]
Follow the instructions to set up MongoDB and the specify the connection details along with your Forge app credentials (aka. client id/secret, optional) in the config json

**Comment by projeffboy** [comment]
Even though I specified the secret, id, and db info in app.json it still gives me that dude's error

**Comment by libvarun** [comment]
Sorry to inform, this repo is no longer maintained.
Alternatively your can try forge-extensions.autodesk.io
